services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
      POSTGRES_DB: n8n
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - '5678:5678'
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npass
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=adminpass
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom-nodes
    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n
      - ./custom-nodes/Random:/home/node/.n8n/custom-nodes/Random
      - ./src/connectors/random-icon.svg:/home/node/.n8n/custom-nodes/Random/random-icon.svg

  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres

volumes:
  postgres_data:
  n8n_data:
